# Generated by Django 2.2.7 on 2019-12-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191213_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='author',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='last_name',
        ),
    ]
